export const CHANGE_INPUT_FIELD = 'CHANGE_INPUT_FIELD';

export const REQUEST_USERS_PENDING = 'REQUEST_USERS_PENDING';

export const REQUEST_USERS_SUCESS = 'REQUEST_USERS_SUCESS';

export const REQUEST_USERS_FAILED = 'REQUEST_USERS_FAILED';